openapi: 3.0.3

info:
  title: Gui o Dev - Ônibus BH API Gateway
  version: 0.1.0
  description: |
    Ônibus BH API Gateway é um serviço utilizado pela Aplicação Web _[Ônibus BH](https://onibusbh.guiodev.com)_.
    No link _[Usando o Ônibus BH API Gateway](https://onibusbh.guiodev.com/docs/api/how-to-use)_ há orientações de como usar o Ônibus BH API Gateway em seu serviço.
  termsOfService: https://onibusbh.guiodev.com/terms-of-service
  contact:
    name: Gui o Dev
    email: guilhermerodrigues680@gmail.com
    url: https://guiodev.com

servers:
  - url: http://localhost:3000
    description: Servidor local
  - url: https://onibusbh.guiodev.com
    description: Servidor de produção
  # - url: https://sandbox-onibusbh.guiodev.com
  #   description: Servidor de homologacao

tags:
  # - name: Default
  #   description: Não agrupadas
  - name: SIU Mobile
    description: Serviços da API do SIU Mobile

paths:
  /api/v1/linhas:
    get:
      summary: Busca todas as linhas do sistema.
      tags:
        - SIU Mobile
      responses:
        "200":
          $ref: "#/components/responses/GetLinhasResponse"
        "500":
          $ref: "#/components/responses/InternalErrorResponse"

  /api/v1/linhas/{cod}/paradas:
    get:
      summary: Busca as paradas de uma linha
      tags:
        - SIU Mobile
      parameters:
        - in: path
          name: cod
          schema:
            type: integer
            minimum: 0
            example: 683
          required: true
          description: Código da linha
      responses:
        "200":
          $ref: "#/components/responses/GetParadasLinhaResponse"
        "400":
          $ref: "#/components/responses/BadRequestErrorResponse"
        "404":
          $ref: "#/components/responses/NotFoundErrorResponse"
        "500":
          $ref: "#/components/responses/InternalErrorResponse"

  /api/v1/paradas:
    get:
      summary: Busca todas as paradas próximas a uma localização
      tags:
        - SIU Mobile
      parameters:
        - in: query
          name: lat
          schema:
            type: number
            example: -19.9228
          required: true
          description: Latitude
        - in: query
          name: lng
          schema:
            type: number
            example: -43.9449
          required: true
          description: Longitude
      responses:
        "200":
          $ref: "#/components/responses/GetParadasResponse"
        "400":
          $ref: "#/components/responses/BadRequestErrorResponse"
        "500":
          $ref: "#/components/responses/InternalErrorResponse"

  /api/v1/paradas/{cod}:
    get:
      summary: Busca uma parada
      tags:
        - SIU Mobile
      parameters:
        - in: path
          name: cod
          schema:
            type: integer
            minimum: 0
            example: 5623
          required: true
          description: Código da parada
      responses:
        "200":
          $ref: "#/components/responses/GetParadaResponse"
        "400":
          $ref: "#/components/responses/BadRequestErrorResponse"
        "404":
          $ref: "#/components/responses/NotFoundErrorResponse"
        "500":
          $ref: "#/components/responses/InternalErrorResponse"

  /api/v1/paradas/{cod}/previssoes:
    get:
      summary: Busca as previssões de uma parada
      tags:
        - SIU Mobile
      parameters:
        - in: path
          name: cod
          schema:
            type: integer
            minimum: 0
            example: 5623
          required: true
          description: Código da parada
      responses:
        "200":
          $ref: "#/components/responses/GetPrevissoesParadaResponse"
        "400":
          $ref: "#/components/responses/BadRequestErrorResponse"
        "404":
          $ref: "#/components/responses/NotFoundErrorResponse"
        "500":
          $ref: "#/components/responses/InternalErrorResponse"

  /api/v1/itinerarios/{cod}:
    get:
      summary: Busca os pontos na superficie terrestre que formam um itinerário
      tags:
        - SIU Mobile
      parameters:
        - in: path
          name: cod
          schema:
            type: integer
            minimum: 0
            example: 48663
          required: true
          description: Código do itinerário
      responses:
        "200":
          $ref: "#/components/responses/GetItinerarioResponse"
        "400":
          $ref: "#/components/responses/BadRequestErrorResponse"
        "404":
          $ref: "#/components/responses/NotFoundErrorResponse"
        "500":
          $ref: "#/components/responses/InternalErrorResponse"

  /api/v1/itinerarios/{cod}/veiculos-tempo-real:
    get:
      summary: Busca a localização de todos os veículos que estão em rota fazendo o itinerario
      tags:
        - SIU Mobile
      parameters:
        - in: path
          name: cod
          schema:
            type: integer
            minimum: 0
            example: 46571
          required: true
          description: Código do itinerário
      responses:
        "200":
          $ref: "#/components/responses/GetVeiculosTempoRealItinerarioResponse"
        "400":
          $ref: "#/components/responses/BadRequestErrorResponse"
        "404":
          $ref: "#/components/responses/NotFoundErrorResponse"
        "500":
          $ref: "#/components/responses/InternalErrorResponse"

components:
  schemas:
    Error:
      type: object
      properties:
        error:
          type: object
          properties:
            code:
              type: number
            codeText:
              type: string
            message:
              type: string
            details:
              type: array
              items:
                type: string

    Linha:
      type: object
      properties:
        cod:
          type: integer
        sgl:
          type: string
        nom:
          type: string
        praca:
          type: string

    Parada:
      type: object
      properties:
        cod:
          type: integer
          format: int32
        siu:
          type: string
        x:
          type: number
        y:
          type: number
        desc:
          type: string
        cor:
          type: integer
          format: int32
          nullable: true

    ParadaLinha:
      type: object
      properties:
        cod:
          type: integer
          format: int32
        end:
          type: string
        siu:
          type: string
        sent:
          type: string
        temVeic:
          type: boolean

    PontoItinerario:
      type: object
      properties:
        coordX:
          type: number
        coordY:
          type: number

    VeiculoTempoRealItinerario:
      type: object
      properties:
        lat:
          type: number
        long:
          type: number
        cor:
          type: integer
          format: int32
          nullable: true
        descricao:
          type: string
        numVeicGestor:
          type: string
        flagAnimacao:
          type: string


  responses:
    GetLinhasResponse:
      description: Lista de linhas
      content:
        application/json:
          schema:
            type: object
            properties:
              linhas:
                type: array
                items:
                  $ref: "#/components/schemas/Linha"
              subLinhas:
                type: array
                items:
                  type: object

    GetParadasLinhaResponse:
      description: Lista de linhas
      content:
        application/json:
          schema:
            type: object
            properties:
              paradas:
                type: array
                items:
                  $ref: "#/components/schemas/ParadaLinha"

    GetParadaResponse:
      description: Parada
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Parada"

    GetParadasResponse:
      description: Lista de paradas próximas
      content:
        application/json:
          schema:
            type: object
            properties:
              paradas:
                type: array
                items:
                  $ref: "#/components/schemas/Parada"
              # postosVenda:
              #   type: array
              #   items:
              #     type: object
              # sucesso:
              #   type: boolean

    GetPrevissoesParadaResponse:
      description: Previssões de uma parada
      content:
        application/json:
          schema:
            type: object
            properties:
              previsoes:
                type: array
                items:
                  type: object
                  properties:
                    sgLin:
                      type: string
                    prev:
                      type: string
                    tpAcess:
                      type: integer
                      format: int32
                    cor:
                      type: integer
                      format: int32
                      nullable: true
                    numVeicGestor:
                      type: string
                    apelidoLinha:
                      type: string
                    codItinerario:
                      type: integer
                      format: int32
              horaConsulta:
                type: string
                example: "02/04/2022 14:47:38"

    GetItinerarioResponse:
      description: Pontos na superficie terrestre que formam o itinerário
      content:
        application/json:
          schema:
            type: object
            properties:
              itinerarios:
                type: array
                items:
                  $ref: "#/components/schemas/PontoItinerario"

    GetVeiculosTempoRealItinerarioResponse:
      description: Localização de todos os veículos que estão em rota fazendo o itinerario
      content:
        application/json:
          schema:
            type: object
            properties:
              veiculos:
                type: array
                items:
                  $ref: "#/components/schemas/VeiculoTempoRealItinerario"

    BadRequestErrorResponse:
      description: Erro nos dados enviados
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Error"

    NotFoundErrorResponse:
      description: Item não encontrado
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Error"

    InternalErrorResponse:
      description: Erro interno
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Error"
